function actionHelper() {
  const ACTIONS = {
    START_LOADING: "START_LOADING",
    END_LOADING: "END_LOADING",
    UPDATE_C_USER: "UPDATE_C_USER",
    RESET_CURRENT_USER: "RESET_CURRENT_USER",
    UPDATE_USER_ACCOUNT: "UPDATE_USER_ACCOUNT",
    RESET_USER_ACCOUNT: "RESET_USER_ACCOUNT",
    UPDATE_EVENT: "UPDATE_EVENT",
    RESET_EVENT: "RESET_EVENT",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    RESET_CATEGORY: "RESET_CATEGORY",
    UPDATE_CRITERIA: "UPDATE_CRITERIA",
    RESET_CRITERIA: "RESET_CRITERIA",
    UPDATE_SCORE: "UPDATE_SCORE",
    RESET_SCORE: "RESET_SCORE",
    UPDATE_CONTESTANT: "UPDATE_CONTESTANT",
    RESET_CONTESTANT: "RESET_CONTESTANT",
  };

  return ACTIONS;
}

export default actionHelper;
